language: node_js
node_js: stable
branches:
  only:
  - source
cache:
  apt: true
  yarn: true
  directories:
  - node_modules
before_install:
- openssl aes-256-cbc -K $encrypted_9494c29a96ee_key -iv $encrypted_9494c29a96ee_iv
  -in ./.travis/id_rsa.enc -out id_rsa -d
- git config --global user.name "lyloou"
- git config --global user.email "lyloou@qq.com"
- git remote set-url origin git@github.com:lyloou/lyloou.github.io.git
- curl -o- -L https://yarnpkg.com/install.sh | bash
- export PATH=$HOME/.yarn/bin:$PATH
- npm install -g hexo-cli
- chmod +x ./run_d.sh
install:
- yarn
script:
- "./run_d.sh"
after_success:
- cd ./public
- git init
- git add .
- git commit -m "Travis CI Auto Builder"
- git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master
env:
  global:
  - GH_REF: github.com/lyloou/lyloou.github.io.git
